# Generated by Django 5.2.7 on 2026-01-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_type",
            field=models.CharField(
                choices=[
                    ("muayene", "Muayene"),
                    ("ameliyat", "Ameliyat"),
                    ("tedavi", "Tedavi"),
                    ("hatirlatma", "Hatirlatma"),
                ],
                max_length=50,
            ),
        ),
    ]
