# mypy.ini
[mypy]
python_version = 3.11

ignore_missing_imports = True
warn_unused_configs = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True

disallow_untyped_defs = True          # require type hints on functions
disallow_incomplete_defs = True       # require type hints for args AND return values
check_untyped_defs = True             # still check inside functions without type hints
no_implicit_optional = True           # Optional must be explicit
strict_equality = True

exclude = (migrations|tests|manage\.py)

# Treat folders as proper Python packages
explicit_package_bases = True
namespace_packages = True

[mypy-*.migrations.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True
