# mypy.ini
[mypy]
python_version = 3.11

ignore_missing_imports = True
warn_unused_configs = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True

# require type hints on functions
# allow untyped defs while codebase is being typed
disallow_untyped_defs = False
# allow incomplete defs while codebase is being typed
disallow_incomplete_defs = False
# skip checking bodies of untyped functions for now
check_untyped_defs = False
# Optional must be explicit
no_implicit_optional = True
strict_equality = True

exclude = (migrations|tests|manage\.py)

# Treat folders as proper Python packages
explicit_package_bases = True
namespace_packages = True

[mypy-*.migrations.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = True

[mypy-djangoCRM.settings_test]
ignore_errors = True
