# Generated by Django 4.2.25 on 2025-10-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_customer_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
