# Generated by Django 4.2.25 on 2025-10-20 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="customer.tag",
            ),
        ),
    ]
