# Generated by Django 4.2.25 on 2025-10-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_alter_customer_assigned_to_alter_customer_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("#FF0000", "red"),
                    ("#800000", "maroon"),
                    ("#FFFF00", "yellow"),
                    ("#008000", "green"),
                    ("#0000FF", "blue"),
                    ("#00FFFF", "Aqua"),
                    ("#800080", "purple"),
                ],
                max_length=7,
            ),
        ),
    ]
