# Generated by Django 4.2.25 on 2025-10-22 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_alter_tag_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_phone",
            field=models.CharField(
                blank=True,
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Provide a valid phone number.",
                        regex="^[\\+]?[0-9]{10,13}$",
                    )
                ],
            ),
        ),
    ]
