# Generated by Django 5.2.7 on 2025-10-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_customer_city_customer_illness_type_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="illness_type",
        ),
    ]
