# Generated by Django 5.2.7 on 2025-10-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_remove_customer_illness_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
