# Generated by Django 5.2.7 on 2025-10-30 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_alter_tag_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="city",
        ),
    ]
