# Generated by Django 5.2.7 on 2025-10-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_remove_customer_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
