# Generated by Django 5.2.7 on 2025-12-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0014_customer_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "active"),
                    ("archived", "archived"),
                    ("quarantine", "quarantine"),
                    ("pool", "pool"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
