# Generated by Django 5.2.7 on 2026-01-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0016_alter_customer_customer_surname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="source",
            field=models.CharField(
                choices=[
                    ("meta", "meta"),
                    ("google ads", "google"),
                    ("instagram", "instagram"),
                    ("whatsapp", "whatsapp"),
                    ("excel", "excel"),
                ],
                default="excel",
                max_length=10,
            ),
        ),
    ]
