REPORT_PRESET_VALUES = ("7", "14", "30", "60")
DEFAULT_REPORT_PRESET = "7"
MAX_REPORT_RANGE_DAYS = 180

APPOINTMENT_STATUS_PENDING = "beklemede"
APPOINTMENT_STATUS_SALES = "satis"
APPOINTMENT_STATUS_NEGATIVE = "olumsuz"

PAYMENT_STATUS_PARTIAL = "kismi"
PAYMENT_STATUS_COMPLETED = "tamamlandi"
PAYMENT_STATUS_CANCELLED = "iptal"
