# Generated by Django 5.2.7 on 2026-06-22 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0003_appointment_report_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notify_assigned_user",
                    models.BooleanField(
                        default=True, verbose_name="Atanmış kullanıcıya gönder"
                    ),
                ),
                (
                    "notify_admins",
                    models.BooleanField(
                        default=False, verbose_name="Aktif adminlere gönder"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reminder_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hatırlatma kuralı",
                "verbose_name_plural": "Hatırlatma kuralları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ReminderOffset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duration", models.DurationField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("before", "Önce"), ("after", "Sonra")],
                        default="before",
                        max_length=10,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offsets",
                        to="reminders.reminderrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zaman offseti",
                "verbose_name_plural": "Zaman offsetleri",
            },
        ),
        migrations.CreateModel(
            name="ReminderCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="reminders.reminderrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Koşul",
                "verbose_name_plural": "Koşullar",
            },
        ),
        migrations.CreateModel(
            name="ScheduledNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("processing", "İşleniyor"),
                            ("sent", "Gönderildi"),
                            ("cancelled", "İptal edildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="events.appointment",
                    ),
                ),
                (
                    "offset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_notifications",
                        to="reminders.reminderoffset",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_notifications",
                        to="reminders.reminderrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zamanlanmış hatırlatma",
                "verbose_name_plural": "Zamanlanmış hatırlatmalar",
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_at"],
                        name="reminders_s_status_3c2c82_idx",
                    )
                ],
            },
        ),
    ]
