# Generated by Django 5.2.7 on 2026-06-22 20:34

import notifications.reminders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminders", "0002_seed_poller_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminderrule",
            name="channels",
            field=models.JSONField(
                default=notifications.reminders.models.default_reminder_channels
            ),
        ),
    ]
