"""
Django settings for djangoCRM project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from drf_spectacular.contrib import rest_framework_simplejwt

from .helpers import SettingsSecretResolver, env_bool, env_list, env_str, load_env_file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


load_env_file(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_STORE_BACKEND = env_str("SECRET_STORE_BACKEND", "env") or "env"
AZURE_KEY_VAULT_URL = env_str("AZURE_KEY_VAULT_URL")
AZURE_MANAGED_IDENTITY_CLIENT_ID = env_str("AZURE_MANAGED_IDENTITY_CLIENT_ID")

_SETTINGS_SECRET_NAMES = {
    "DJANGO_SECRET_KEY": "django-secret-key",
    "DJANGO_CACHE_URL": "django-cache-url",
    "FLOWER_BASIC_AUTH": "flower-basic-auth",
    "CELERY_RESULT_BACKEND": "celery-result-backend",
    "REDIS_PASSWORD": "redis-password",
    "CELERY_BROKER_URL": "celery-broker-url",
    "RABBITMQ_DEFAULT_PASS": "rabbitmq-default-pass",
    "RABBITMQ_DEFAULT_USER": "rabbitmq-default-user",
    "POSTGRES_PASSWORD": "postgres-password",
    "POSTGRES_USER": "postgres-user",
}

SETTINGS_SECRET_RESOLVER = SettingsSecretResolver(
    backend=SECRET_STORE_BACKEND,
    vault_url=AZURE_KEY_VAULT_URL,
    managed_identity_client_id=AZURE_MANAGED_IDENTITY_CLIENT_ID,
    secret_names=_SETTINGS_SECRET_NAMES,
)


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SETTINGS_SECRET_RESOLVER.get_secret("DJANGO_SECRET_KEY", required=True)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", False)
# DEBUG = True

# ALLOWED_HOSTS = ["*"]
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts.apps.AccountsConfig",
    "customer.apps.CustomerConfig",
    "events.apps.EventsConfig",
    "exporter.apps.ExporterConfig",
    "importer.apps.ImporterConfig",
    "notifications.apps.NotificationsConfig",
    "products.apps.ProductsConfig",
    "reports.apps.ReportsConfig",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "rest_framework",
    "django_filters",
    "corsheaders",
    "drf_standardized_errors",
    "drf_yasg",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "djangoCRM.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoCRM.wsgi.application"

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    # "PAGE_SIZE": 20,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authenticate.CustomAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "drf_standardized_errors.handler.exception_handler",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "CRM API",
    "DESCRIPTION": "API documentation for CRM project",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB"),
        "USER": SETTINGS_SECRET_RESOLVER.get_secret("POSTGRES_USER", required=True),
        "PASSWORD": SETTINGS_SECRET_RESOLVER.get_secret(
            "POSTGRES_PASSWORD", required=True
        ),
        "HOST": os.getenv("POSTGRES_HOST"),
        "PORT": os.getenv("POSTGRES_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "accounts.CustomUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Europe/Istanbul"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
EXPORT_FILES_ROOT = MEDIA_ROOT / "exports"

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DJANGO_CACHE_URL = SETTINGS_SECRET_RESOLVER.get_secret("DJANGO_CACHE_URL")

CACHES = {
    "default": (
        {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": DJANGO_CACHE_URL,
            "KEY_PREFIX": "djangocrm",
            "TIMEOUT": 120,
        }
        if DJANGO_CACHE_URL
        else {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "login-throttle",
            "TIMEOUT": 120,
        }
    )
}

EMAIL_BACKEND = env_str("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_TIMEOUT = int(env_str("EMAIL_TIMEOUT", "10") or "10")
MAIL_CONFIG_TEST_SESSION_TTL_SECONDS = int(
    env_str("MAIL_CONFIG_TEST_SESSION_TTL_SECONDS", "600") or "600"
)
SERVER_EMAIL = env_str("DEFAULT_FROM_EMAIL")
DEFAULT_FROM_EMAIL = SERVER_EMAIL

FLOWER_BASIC_AUTH = SETTINGS_SECRET_RESOLVER.get_secret("FLOWER_BASIC_AUTH")
REDIS_PASSWORD = SETTINGS_SECRET_RESOLVER.get_secret("REDIS_PASSWORD")
RABBITMQ_DEFAULT_USER = SETTINGS_SECRET_RESOLVER.get_secret("RABBITMQ_DEFAULT_USER")
RABBITMQ_DEFAULT_PASS = SETTINGS_SECRET_RESOLVER.get_secret("RABBITMQ_DEFAULT_PASS")

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(hours=4),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "AUTH_COOKIE": "access_token",  # Cookie name. Enables cookies if value is set.
    "AUTH_COOKIE_REFRESH_TOKEN": "refresh_token",
    "AUTH_COOKIE_DOMAIN": None,  # A string like "example.com", or None for standard domain cookie.
    # "AUTH_COOKIE_SECURE": False,  # Whether the auth cookies should be secure (https:// only).
    "AUTH_COOKIE_SECURE": not DEBUG,
    "AUTH_COOKIE_PATH": "/",  # The path of the auth cookie.
    "AUTH_COOKIE_SAMESITE": "Lax",
}
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS")

CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

# CELERY
CELERY_BROKER_URL = SETTINGS_SECRET_RESOLVER.get_secret(
    "CELERY_BROKER_URL", required=True
)
CELERY_RESULT_BACKEND = SETTINGS_SECRET_RESOLVER.get_secret(
    "CELERY_RESULT_BACKEND", default=CELERY_BROKER_URL, required=True
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 15  # CELERY RESULTLARIN RAM DEN SILINECEGI SURE

# LOCAL de calisirken commente al HTTP ve HSTS yi
# HTTP SETTINGS
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", True)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", True)
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# HSTS SETTINGS
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
