# Generated by Django 5.2.7 on 2026-06-20 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_key", models.CharField(max_length=100)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="imports/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Bekliyor"),
                            ("PREVIEWED", "Önizlendi"),
                            ("RUNNING", "Çalışıyor"),
                            ("DONE", "Tamamlandı"),
                            ("FAILED", "Başarısız"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("skipped_count", models.IntegerField(default=0)),
                ("preview_result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.IntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                ("normalized_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Başarılı"),
                            ("error", "Hatalı"),
                            ("skipped", "Atlandı"),
                            ("duplicate", "Tekrar"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                ("errors", models.JSONField(default=list)),
                ("object_id", models.IntegerField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="importer.importjob",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index"],
            },
        ),
    ]
